# Generated by Django 5.0.7 on 2024-07-28 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productenter',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productenter',
            name='old_quantity',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='productimg',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='Goods.product'),
        ),
    ]
