# Generated by Django 5.0.7 on 2024-08-02 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0005_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('generate_code', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InfoInstaPhoto',
            fields=[
                ('generate_code', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Goods.info')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
