# Generated by Django 5.0.7 on 2024-08-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0006_info_infoinstaphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
