# Generated by Django 5.0.7 on 2024-08-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0007_info_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
